name: Auto Title PR with Gemini

on:
  pull_request:
    types: [opened, edited, labeled]

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-and-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate and Generate PR Content
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-token: ${{ secrets.GEMINI_API_KEY }}
          