name: Auto Title PR with Gemini

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  generate-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate PR Title
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-token: ${{ secrets.GEMINI_API_KEY }}
          